// Generated by CoffeeScript 1.4.0
(function() {

  if (typeof Panoko === "undefined" || Panoko === null) {
    window.Panoko = {};
  }

  Panoko.TimeField = React.createFactory(React.createClass({
    timeString: function(milliseconds) {
      var d;
      d = new Date(milliseconds * 1000);
      return s.sprintf("%02d:%02d:%02d", d.getHours(), d.getMinutes(), d.getSeconds());
    },
    render: function() {
      return DOM.td({
        "class": 'table-time'
      }, this.timeString(this.props.fact.timestamp_start));
    }
  }));

}).call(this);
